services:
  - type: web
    name: sequencia-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sequencia-db
          property: connectionString

databases:
  - name: sequencia-db
    plan: free

staticSites:
  - name: sequencia-ui
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "predictionui/dist"
