"""Add Article, Keyword, and ArticleKeyword

Revision ID: 3e59e8398e86
Revises: d3a08f87d621
Create Date: 2025-04-19 18:42:42.659779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e59e8398e86'
down_revision: Union[str, None] = 'd3a08f87d621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('article_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_keywords_id'), 'article_keywords', ['id'], unique=False)
    op.add_column('keywords', sa.Column('text', sa.String(), nullable=True))
    op.drop_constraint('keywords_word_key', 'keywords', type_='unique')
    op.create_index(op.f('ix_keywords_text'), 'keywords', ['text'], unique=True)
    op.drop_column('keywords', 'word')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_keywords_text'), table_name='keywords')
    op.create_unique_constraint('keywords_word_key', 'keywords', ['word'])
    op.drop_column('keywords', 'text')
    op.drop_index(op.f('ix_article_keywords_id'), table_name='article_keywords')
    op.drop_table('article_keywords')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
