"""add_slug_to_category

Revision ID: 493e7b9739f2
Revises: 3e59e8398e86
Create Date: 2025-04-26 18:36:02.816427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e7b9739f2'
down_revision: Union[str, None] = '3e59e8398e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
