"""revert back slug

Revision ID: b455554da2a7
Revises: 493e7b9739f2
Create Date: 2025-04-26 19:16:04.653022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b455554da2a7'
down_revision: Union[str, None] = '493e7b9739f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_slug', table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###
