"""create admin column

Revision ID: d3a08f87d621
Revises: 5f7db849fe80
Create Date: 2025-04-19 17:19:54.370795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a08f87d621'
down_revision: Union[str, None] = '5f7db849fe80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ Set False for all existing NULL values
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")

    # ✅ Now make column NOT NULL
    op.alter_column('users', 'is_admin',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
