"""fresh schema migration

Revision ID: e98f5087b205
Revises: 
Create Date: 2025-04-17 12:45:25.820255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98f5087b205'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'predicted_probability')
    op.drop_column('questions', 'actual_range_min')
    op.drop_column('questions', 'actual_outcome')
    op.drop_column('questions', 'actual_range_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('actual_range_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('actual_outcome', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('actual_range_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('predicted_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
