"""include new fields

Revision ID: f5770bfd7aaf
Revises: 02b364c394e8
Create Date: 2025-04-27 02:57:51.561918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5770bfd7aaf'
down_revision: Union[str, None] = '02b364c394e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('approval_rating', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sentiment_score')
    op.drop_column('articles', 'approval_rating')
    # ### end Alembic commands ###
